# Generated by Django 3.2.11 on 2022-02-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_category_status_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='ензу',
            new_name='type',
        ),
    ]
