# Generated by Django 3.2.11 on 2022-02-28 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_covid'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='covid',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
